// Generated by scripts/fetch-menu.mjs — do not edit by hand.
// Source: the client's live Dishio menu (cm8iyo4qz00cxm3etw7ravdkg).
// Re-run `node scripts/fetch-menu.mjs` after they change it.
//
// 7 sections, 233 dishes, pulled 2026-09-01.

export type MenuItem = {
  name: string;
  desc?: string;
  /** Absent when the kitchen lists the dish without a price. */
  price?: string;
};

export type MenuSubsection = { name: string; items: MenuItem[] };

export type MenuCategory = {
  id: string;
  name: string;
  subsections: MenuSubsection[];
};

export const menuCategories: MenuCategory[] = [
  {
    "id": "main-menu",
    "name": "Main Menu",
    "subsections": [
      {
        "name": "Appetizers",
        "items": [
          {
            "name": "Arancini",
            "desc": "Fried Saffron Risotto Stuffed with Fontina and served with Saffron Aioli",
            "price": "14"
          },
          {
            "name": "Beef Carpaccio",
            "desc": "Capers, Shallots, Soy-Mustard Vinaigrette",
            "price": "16"
          },
          {
            "name": "Peach Caprese",
            "desc": "Prosciutto and Burrata served with Roasted Peaches and Pistachios",
            "price": "21"
          },
          {
            "name": "Bread & Butter",
            "desc": "*Add Delice de Bourgogne for an additional $9",
            "price": "6"
          },
          {
            "name": "Chicken Noodle Soup",
            "desc": "Fresh Pasta, Slow-Simmered Broth, Roasted Chicken and Herbs",
            "price": "16"
          },
          {
            "name": "BBQ Shrimp",
            "desc": "Head on Shrimp Blackened and Smothered in Cajun BBQ",
            "price": "24"
          },
          {
            "name": "Hamachi Tartare",
            "desc": "Fried Potato Dauphinoise, Truffle Aioli and Fresh Chives",
            "price": "23"
          },
          {
            "name": "Caesar Salad",
            "desc": "Classic Caesar Salad with White Anchovies and Parmesan Reggiano",
            "price": "15"
          }
        ]
      },
      {
        "name": "Pasta",
        "items": [
          {
            "name": "Eggplant Ravioli",
            "desc": "Grilled Eggplant Stuffed Pasta with Smoked Ricotta Salata and Arugula",
            "price": "34"
          },
          {
            "name": "Spaghetti & Meatball",
            "desc": "Like Your Nonna Made it",
            "price": "27"
          },
          {
            "name": "Fra Diavolo",
            "desc": "Head-On Shrimp & Mussels served in a Spicy Marinara with Squid Ink Linguine Fini",
            "price": "39"
          }
        ]
      },
      {
        "name": "Mains",
        "items": [
          {
            "name": "Bistecca Fiorentina",
            "desc": "T-bone Steak with Roasted Garlic and Tuscan Potatoes",
            "price": "116"
          },
          {
            "name": "Fresh Catch",
            "desc": "Rotating Selection prepared with Seasonal Ingredients",
            "price": "MP"
          },
          {
            "name": "Eggplant Amatriciana",
            "desc": "Fried Eggplant with Broccolini, Amatriciana Sauce and Parmesan Foam",
            "price": "29"
          },
          {
            "name": "Roasted Chicken",
            "desc": "Half or Whole Roasted Chicken served with Pureed Mushrooms and Truffled Chicken Jus",
            "price": "36"
          },
          {
            "name": "Charred Pork Chop",
            "desc": "Duroc Heritage Pork with Parsnip, Farro, and Charred Agrodolce Onions",
            "price": "47"
          }
        ]
      },
      {
        "name": "Mains with Frites",
        "items": [
          {
            "name": "Steak frites",
            "desc": "Hanger Steak Served with Sauce Au Poive or Truffle Butter",
            "price": "59"
          },
          {
            "name": "Le Classic Cheeseburger",
            "desc": "Roasted Tomato, Bibb Lettuce, Mustard, Red Onion and Pickles",
            "price": "25"
          },
          {
            "name": "Rebellion Burger",
            "desc": "Allan Bentons Bacon, Onion Jam, Sauerkraut, Truffle Aioli And Delice de Bourgogne",
            "price": "29"
          },
          {
            "name": "Moules Frites",
            "desc": "Steamed Mussels a La Pernod, with Leeks and Allan Bentons Bacon",
            "price": "35"
          }
        ]
      },
      {
        "name": "Sides",
        "items": [
          {
            "name": "Tuscan Potatoes",
            "desc": "Fried Red Bliss Potatoes with Garlic Butter and Tonnato Sauce",
            "price": "14"
          },
          {
            "name": "Broccolini",
            "desc": "Sautéed with Dried Currants and Sliced Almonds",
            "price": "10"
          }
        ]
      },
      {
        "name": "Desserts",
        "items": [
          {
            "name": "Key Lime Pie",
            "desc": "Key Lime Semi-Freddo with Toasted Graham Cracker and Ginger",
            "price": "13"
          },
          {
            "name": "Tiramisu",
            "price": "9"
          },
          {
            "name": "Palm Sugar Ice Cream",
            "desc": "Heritage Coconut Palm Sugar Ice Cream",
            "price": "8"
          },
          {
            "name": "Creme Brulee",
            "desc": "Caramelized Sugar atop a Lavender infused Cream Custard",
            "price": "13"
          },
          {
            "name": "Pot de Creme",
            "desc": "Cayenne spiced chocolate mousse with whipped cream and chocolate granola",
            "price": "13"
          }
        ]
      }
    ]
  },
  {
    "id": "brunch",
    "name": "Brunch",
    "subsections": [
      {
        "name": "Brunch",
        "items": [
          {
            "name": "Avocado Toast",
            "desc": "Toasted Sourdough with Fresh Avocado Tahini, Pickled Red Onion, Radish and Poached Egg",
            "price": "21"
          },
          {
            "name": "Rebel Breakfast",
            "desc": "Two Eggs Cooked Any Style, Smoked bacon and Fried Red Potatoes",
            "price": "18"
          },
          {
            "name": "French Omelette",
            "desc": "Soft Cooked Omelette gently folded and filled with Fine Herbs, Parmesan and a touch of Butter",
            "price": "14"
          },
          {
            "name": "Proscuitto Benedict",
            "desc": "Homemade English Muffin, Hollandaise Sauce, Poached Egg and Fried Red Potatoes",
            "price": "18"
          },
          {
            "name": "Shrimp Benedict",
            "desc": "Homemade English Muffin, Hollandaise Sauce, Poached Egg and Fried Red Potatoes",
            "price": "22"
          },
          {
            "name": "Steak Frites",
            "desc": "Bistro Cut served with Sauce Au Poivre",
            "price": "31"
          },
          {
            "name": "Ham & Eggs",
            "desc": "Sliced Prosciutto Ham with Two Eggs Sunny Side Up, Toasted Sourdough and Burrata",
            "price": "23"
          },
          {
            "name": "French Toast",
            "desc": "Dulche de Leche, Roasted Apples, Pickled Fennel and Maple Syrup",
            "price": "20"
          },
          {
            "name": "Baked Eggs",
            "desc": "Chicken and Bacon with Sauteed Kale, Roasted Potato, Tomato, and Arugula Salad and Ricotta Salata",
            "price": "22"
          },
          {
            "name": "Shrimp & Grits",
            "desc": "Blackend Shrimp with Grits, Confit Leeks and Bloody Mary Broth",
            "price": "26"
          },
          {
            "name": "Rebellion Burger",
            "desc": "Allan Bentons Bacon, Onion Jam, Sauerkraut, Truffle Aioli and Brillat Savarin",
            "price": "29"
          }
        ]
      },
      {
        "name": "Sides",
        "items": [
          {
            "name": "Bread and Butter",
            "price": "6"
          },
          {
            "name": "Grits",
            "desc": "Marsh Hen Hill Stone Grits with Cheese & Butter",
            "price": "10"
          },
          {
            "name": "Two Eggs",
            "desc": "Cooked any style",
            "price": "6"
          },
          {
            "name": "Bacon",
            "price": "13"
          },
          {
            "name": "Yogurt Parfait",
            "desc": "Honey Infused Yogurt with Fresh Fruit",
            "price": "11"
          }
        ]
      },
      {
        "name": "Brunch Cocktails",
        "items": [
          {
            "name": "Bottomless Mimosas",
            "desc": "*with purchase of an entree",
            "price": "20"
          },
          {
            "name": "The Guillotine",
            "desc": "The Lost Explorer 8-year Mezcal, Smoked Altered Melon Liqueur, Cointreau, Agave, Black Lava Salt and Pepper Rim",
            "price": "17"
          },
          {
            "name": "Bloody Marie",
            "desc": "Charleston Bloody Mary Mix, Allan Benton's Bacon-Washed Bourbon, Rosemary Stock, Accoutrements",
            "price": "16"
          },
          {
            "name": "Wake N' Bake espresso Martini",
            "desc": "Citrus-Zested Prairie Organice Vodka, Mr. Black Coffee Liqueur, Tempus Fugit Creme de Cacao, Giffard Vanilla, Faretti Biscotti, Barrel-Aged Maple Syrup",
            "price": "17"
          },
          {
            "name": "Versailles Garden",
            "desc": "Citadelle Viva La Cornichon Gin, Massenez Creme de Cassis, Lavender Sage Honey, Coconut Water, Fruit Caviar",
            "price": "17"
          }
        ]
      }
    ]
  },
  {
    "id": "cocktails-menu",
    "name": "Cocktails Menu",
    "subsections": [
      {
        "name": "Signature Cocktails",
        "items": [
          {
            "name": "The Guillotine",
            "desc": "The Lost Explorer 8yr Mezcal, Artonic Melon Liqueur, Cointreau, Agave, Black Lava Salt and Pepper Rim",
            "price": "17"
          },
          {
            "name": "Marie Antoinette",
            "desc": "44 North Huckleberry Vodka, Giffard Creme de Mure, Vanilla Demerara, Mascarpone Cream, Graham Cracker Rim.",
            "price": "18"
          },
          {
            "name": "Tennis Court Oath",
            "desc": "Sesame Oil Washed Planteray 3 Star Rum, Montenegro, Coconut Creme, Chilli Oil, Toasted Coconut Latik",
            "price": "17"
          },
          {
            "name": "King Louis",
            "desc": "Brown Butter and Pecan infused Bache Tre Kors Cognac, Benedictine, Vanilla Demerara, House Bitters",
            "price": "18"
          },
          {
            "name": "Bastille Blanc",
            "desc": "Ford's Gin, Genepy, Vermouth, Rosemary",
            "price": "16"
          },
          {
            "name": "Versailles Garden",
            "desc": "Citadelle Viva La Cornichon Gin, Massenez Creme de Cassis, Lavender Sage Honey, Coconut Water, Fruit Caviar",
            "price": "17"
          }
        ]
      },
      {
        "name": "David Bowie Essentials",
        "items": [
          {
            "name": "Life on Mars",
            "desc": "Lairds 7.5 Year Apple Brandy, Kanade White Peach, Angostura Amaro, Orgeat, Amaro Nonino, Graham Cracker Dust, Fee Foam",
            "price": "17"
          },
          {
            "name": "Young American",
            "desc": "Cazcabel Reposado, Savoia, Jeppsons Malort, Orange Blossom Water, Yerba Mate Syrup, Cardamom, Campari Dust",
            "price": "16"
          },
          {
            "name": "Major Tom",
            "desc": "Isolation Proof Strawberry Rhubarb, Darroze Blanche Armagnac, Green Chartreuse, Italicus, Elderflower, Tonic, Ling Hi Mui Powder.",
            "price": "18"
          },
          {
            "name": "Ashes to Ashes",
            "desc": "Singani 63, Jerk and Vadovan Syrup, Vanilla, Egg White, Cinnamon Dust",
            "price": "18"
          },
          {
            "name": "Ziggy Stardust",
            "desc": "Citadelle Summer Garden Gin, Giffard Apricot, Coconut Cream, Butterfly Pea Tea and Coconut water Cube.",
            "price": "19.99"
          },
          {
            "name": "Rebel Rebel",
            "desc": "Smith and Cross Navy Strength Rum, Coffee Acid, Roasted Peanut Cola Syrup, Vanilla-Cherry Cayenne Foam, OFTD Overproof rum float",
            "price": "17"
          }
        ]
      },
      {
        "name": "Rebellious Classics",
        "items": [
          {
            "name": "Sidecar",
            "desc": "Bache Tre Kors VS cognac, Kanade Yuzu, Cointreau, Lemon, Cinnamon Sugar Rim",
            "price": "16"
          },
          {
            "name": "Espresso Martini",
            "desc": "Luksusowa Vodka, Borghetti Espresso Liqueur, Giffard Vanilla, Tempis Fugit Creme De Cacao",
            "price": "18"
          },
          {
            "name": "Gimlet",
            "desc": "Hanson's Mandarin Vodka, Mint, Lime, Simple",
            "price": "15"
          },
          {
            "name": "Daiquiri",
            "desc": "Hamilton’s Demerara 86 Rum, Vanilla Demerara Syrup, Lime, Tempus Fugit Creme de Banane",
            "price": "16"
          }
        ]
      },
      {
        "name": "Mocktails",
        "items": [
          {
            "name": "The Spicy Coconut",
            "desc": "Coconut Water, Coconut Cream, Ginger & Lemon",
            "price": "12"
          },
          {
            "name": "Tamarindo",
            "desc": "Coriander & Tamarind Syrup, Pineapple, Q Club Soda",
            "price": "13"
          },
          {
            "name": "Americola",
            "desc": "Coca Cola Reduction, Iced Espresso, Vanilla Demerarra",
            "price": "12"
          }
        ]
      }
    ]
  },
  {
    "id": "wine-beer-by-the-glass",
    "name": "Wine & Beer by the Glass",
    "subsections": [
      {
        "name": "Sparkling",
        "items": [
          {
            "name": "N.V. Caneva da Nani",
            "desc": "Col Fondo Glera Veneto, Italy",
            "price": "16"
          }
        ]
      },
      {
        "name": "White",
        "items": [
          {
            "name": "2024 Cultivar",
            "desc": "Sauvignon Blanc Napa Valley, California",
            "price": "14"
          },
          {
            "name": "2025 De Forville",
            "desc": "Ca' del Buc Chardonnay Piemonte, Italy",
            "price": "16"
          },
          {
            "name": "2024 Brisa Suave",
            "desc": "Vinho Verde Branco Minho, Portugal",
            "price": "15"
          }
        ]
      },
      {
        "name": "Rosé",
        "items": [
          {
            "name": "2024 Bixigu Txakolina Rose",
            "desc": "Basque, Spain Hondarrabi Zuri Hondarrabi Beltza",
            "price": "16"
          }
        ]
      },
      {
        "name": "Orange",
        "items": [
          {
            "name": "2024 Azimut Brisat",
            "desc": "Catalonia, Spain Parellada Sumoll Blanc Garnatxa Blanca Moscatell",
            "price": "16"
          }
        ]
      },
      {
        "name": "Red",
        "items": [
          {
            "name": "2021 Domaine Guion",
            "desc": "Cuvee Candide Loire Valley, France Cabernet Franc",
            "price": "17"
          },
          {
            "name": "2024 Domaine Dubost",
            "desc": "Beaujolais-Lantignie Rouge Gamay Beaujolais, France",
            "price": "17"
          },
          {
            "name": "2022 Bois de Boursan",
            "desc": "Le Petit Oursan Grenache, Merlot, Syrah Rhone Valley, France",
            "price": "15"
          },
          {
            "name": "2024 Brea",
            "desc": "Cabernet Sauvignon Paso Robles, California",
            "price": "20"
          }
        ]
      },
      {
        "name": "Beers",
        "items": [
          {
            "name": "Sideward Brewing",
            "desc": "Moon Boots American IPA Orlando, FL",
            "price": "11"
          },
          {
            "name": "Ravenous Pig (draft)",
            "desc": "Working Man Porter Orlando, Florida",
            "price": "10"
          },
          {
            "name": "Kronenbourg 1664 (can)",
            "desc": "Canned Kronenbourg 1664",
            "price": "7"
          },
          {
            "name": "Civil Society Fresh IPA draft",
            "desc": "Hazy India Pale Ale Jupiter, FL",
            "price": "10"
          },
          {
            "name": "Buenaveza Salt & Lime Lager",
            "desc": "Stone Brewing Draft",
            "price": "8"
          }
        ]
      }
    ]
  },
  {
    "id": "cider",
    "name": "Cider",
    "subsections": [
      {
        "name": "Bottled Cider",
        "items": [
          {
            "name": "2023 Etienne Dupont",
            "desc": "Cidre Bouche Brut de Normandie 375 ml bottle",
            "price": "21"
          }
        ]
      },
      {
        "name": "Canned Cider",
        "items": [
          {
            "name": "Cider Creek Cider",
            "price": "7"
          }
        ]
      }
    ]
  },
  {
    "id": "wine-menu",
    "name": "Wine Menu",
    "subsections": [
      {
        "name": "Burgundy, Champagne & Beaujolais",
        "items": [
          {
            "name": "N.V. Pertois-Moriset",
            "desc": "L'Assemblage Champagne Pinot Noir and Chardonnay Sparkling Wine",
            "price": "146"
          },
          {
            "name": "2023 00 Wines",
            "desc": "Pommard 1er Cru Clos des Epenots Pinot Noir Red Wine",
            "price": "398"
          },
          {
            "name": "2023 Domaine Fichet",
            "desc": "Tradition Pinot Noir Bourgogne Red Wine",
            "price": "75"
          },
          {
            "name": "2023 Guy Breton",
            "desc": "Morgon Gamay Red Wine",
            "price": "112"
          },
          {
            "name": "2012 Bouchard Pere & Fils",
            "desc": "Nuits-Saint-Georges Premier Cru Burgundy Pinot Noir",
            "price": "374"
          },
          {
            "name": "2022 Domaine du Granit",
            "desc": "Tradition Moulin-a-Vent Beaujolais, France Gamay Red Wine",
            "price": "85"
          },
          {
            "name": "2023 Guy Breton",
            "desc": "Chiroubles Beaujolais, France Gamay Red Wine",
            "price": "123"
          },
          {
            "name": "2023 Guy Breton",
            "desc": "Cote de Brouilly Beaujolais, France Gamay Red Wine",
            "price": "114"
          },
          {
            "name": "2023 Guy Breton",
            "desc": "“Vielles Vignes” Morgon Gamay Red Wine",
            "price": "112"
          },
          {
            "name": "2021 Yuka & Clotaire Michal",
            "desc": "Songe d’Une Nuit d’Automne Gamay Red Wine",
            "price": "121"
          },
          {
            "name": "2021 Domaine De Bellene",
            "desc": "Savigny-les-Beaune Blanc Chardonnay White Wine",
            "price": "174"
          }
        ]
      },
      {
        "name": "Bordeaux & Southwest France",
        "items": [
          {
            "name": "2011 Chateau Massereau",
            "desc": "Cuvee K Bordeaux Merlot, Cabernet Franc, Cabernet Sauvignon, Petit Verodt Red Wine",
            "price": "118"
          },
          {
            "name": "2019 Chateau le Coteau",
            "desc": "Margaux Bordeaux, France Cabernet Sauvignon, Merlot, Cabernet Franc, Petit Verdot Red Wine",
            "price": "137"
          },
          {
            "name": "2018 Chateau Trottevielle",
            "desc": "Saint-Emilion Cabernet Franc, Merlot, Cabernet Sauvignon Red Wine",
            "price": "300"
          },
          {
            "name": "2017 Chateau De Chambert",
            "desc": "Cahors Grand Vin Malbec Red Wine",
            "price": "148"
          },
          {
            "name": "2019 Clos Siguier",
            "desc": "Cahors Malbec, Tannat Red Wine",
            "price": "59"
          },
          {
            "name": "2023 Chateau Lestignac",
            "desc": "'Michel-Michel- Orange VDF Sauvignon Gris, Sauvignon Blanc, Muscadelle Orange Wine",
            "price": "85"
          },
          {
            "name": "2021 Closerie Des Moussis",
            "desc": "Moineaux Cabernet Sauvignon, Merlot, Cabernet Franc Red Wine",
            "price": "221"
          }
        ]
      },
      {
        "name": "Rhone Valley, Provence & Languedoc",
        "items": [
          {
            "name": "2022 Domaine de Boisseyt",
            "desc": "Cote Blonde Cote Rotie Rhone Syrah, Viognier Red Wine",
            "price": "392"
          },
          {
            "name": "2020 Domaine Francois Villard",
            "desc": "Le Grand Vallon Condrieu Viognier White Wine",
            "price": "162"
          },
          {
            "name": "2023 Matthieu Barret",
            "desc": "‘Petit Ours’ Cotes du Rhone Syrah Red Wine",
            "price": "80"
          }
        ]
      },
      {
        "name": "Loire Valley",
        "items": [
          {
            "name": "2023 Domaine des Chasseignes",
            "desc": "'Les Montaignes' Sancerre Blanc Sauvignon Blanc",
            "price": "154"
          },
          {
            "name": "2024 Saumur Les Moulins",
            "desc": "Cabernet Franc Loire Valley Red Wine",
            "price": "75"
          },
          {
            "name": "2023 Domaine Emmanuel Haget",
            "desc": "Preambules Pet Nat Cabernet Franc and Chenin Blanc Loire Valley, France Sparkling Wine",
            "price": "88"
          },
          {
            "name": "2022 Gaspard",
            "desc": "Central France Pinot Noir Red Wine",
            "price": "64"
          },
          {
            "name": "2022 Domaine Huet",
            "desc": "Vouvray Le Haut Lieu Sec Chenin Blanc White Wine",
            "price": "119"
          }
        ]
      },
      {
        "name": "Alsace, Savoy & The Jura",
        "items": [
          {
            "name": "2022 Les Valseuses",
            "desc": "Sanza Nocturne Red Grenache Jura Red Wine",
            "price": "112"
          },
          {
            "name": "2023 Denis&Didier Berthollier",
            "desc": "Chignin Vieilles Vignes Savoy, France Jacquere White Wine",
            "price": "78"
          },
          {
            "name": "2021 Denis&Didier Berthollier",
            "desc": "Chignin Bergeron Les Salins Savoy, France Roussanne White Wine",
            "price": "133"
          },
          {
            "name": "2021 Valentin Zusslin",
            "desc": "Le Schild Riesling Alsace, France White Wine",
            "price": "112"
          },
          {
            "name": "2022 Domaine Partagé",
            "desc": "Les Christine Roussanne White Wine",
            "price": "286"
          }
        ]
      },
      {
        "name": "Italy",
        "items": [
          {
            "name": "2024 Bruno Verdi",
            "desc": "Oltrepo Pavese Pinot Grigio Piedmont, Italy",
            "price": "71"
          },
          {
            "name": "2023 Folicello IL Bianco",
            "desc": "Ancestral Bianco Montuni, Pinot Blanc, Trebbiano Emilia-Romagna, Italy Sparkling Wine",
            "price": "55"
          },
          {
            "name": "2024 Orsola",
            "desc": "Monferrato Rosso Barbera, Cabernet Sauvignon Piedmont, Italy Red Wine",
            "price": "67"
          },
          {
            "name": "2019 Nadia Curto",
            "desc": "Barolo Piedmont, Italy",
            "price": "185"
          },
          {
            "name": "2020 Sassodisole",
            "desc": "Brunello di Montalcino Tuscany, Italy Red Wine",
            "price": "148"
          },
          {
            "name": "2022 II Vulcano di Elisa",
            "desc": "Nerello Mascalese Sicily, Italy Red Wine",
            "price": "80"
          },
          {
            "name": "N.V. Federico Orsi",
            "desc": "Posca Bianca Emilia-Romagna, Italy White Wine",
            "price": "89"
          },
          {
            "name": "2023 Fabrica di San Martino",
            "desc": "Costa Toscana Rosso Arcipressi Tuscany, Italy Red WIne",
            "price": "97"
          },
          {
            "name": "2024 Gioventu",
            "desc": "Chianti DOCG Sangiovese Tuscany, Italy Red Wine",
            "price": "56"
          }
        ]
      },
      {
        "name": "New World Wines",
        "items": [
          {
            "name": "2023 00 Wines",
            "desc": "'VGW' Chardonnay Willamette Valley, Oregon",
            "price": "253"
          },
          {
            "name": "2023 Brea",
            "desc": "Cabernet Sauvignon Margarita Vineyard Paso Robles, California Red Wine",
            "price": "75"
          },
          {
            "name": "2023 00 Wines",
            "desc": "'VGR' Pinot Noir Willamette Valley, Oregon Red Wine",
            "price": "290"
          },
          {
            "name": "2023 Aperture",
            "desc": "Cabernet Sauvignon Alexander Valley, California Red Wine",
            "price": "204"
          },
          {
            "name": "2023 Brea",
            "desc": "Chardonnay Central Coast, California White Wine",
            "price": "63"
          },
          {
            "name": "2017 Domaine Serene",
            "desc": "Yamhill Cuvee Pinot Noir Willamette Valley, Oregon Red Wine",
            "price": "119"
          },
          {
            "name": "2022 The Hilt Estate",
            "desc": "Chardonnay Central Coast, California White Wine",
            "price": "112"
          }
        ]
      }
    ]
  },
  {
    "id": "spirits-menu",
    "name": "Spirits Menu",
    "subsections": [
      {
        "name": "Vodka",
        "items": [
          {
            "name": "44 North Potato Vodk",
            "desc": "(Idaho)",
            "price": "MP"
          },
          {
            "name": "Crop Cucumber Vodka",
            "desc": "(New York)",
            "price": "MP"
          },
          {
            "name": "Ketel One",
            "price": "MP"
          },
          {
            "name": "Hansons Mandarin",
            "desc": "(Sonoma)",
            "price": "MP"
          },
          {
            "name": "Luksusowa Vodka",
            "desc": "Potato Vodka Triple Distilled (Poland)",
            "price": "MP"
          },
          {
            "name": "Belvedere Single Estate",
            "price": "MP"
          },
          {
            "name": "Grey Goose",
            "price": "MP"
          },
          {
            "name": "Titos (Texas)",
            "price": "MP"
          }
        ]
      },
      {
        "name": "Gin",
        "items": [
          {
            "name": "Martin Millers 9 Moons",
            "price": "MP"
          },
          {
            "name": "The Botanist",
            "desc": "(Scotland)",
            "price": "MP"
          },
          {
            "name": "Gin Lane Summer Garden",
            "price": "MP"
          },
          {
            "name": "Hendrick’s Gin",
            "desc": "(Scotland)",
            "price": "MP"
          },
          {
            "name": "Barr Hill Gin",
            "desc": "(Vermont)",
            "price": "MP"
          },
          {
            "name": "Ford’s Gin",
            "price": "MP"
          },
          {
            "name": "Tanqueray 10",
            "price": "MP"
          },
          {
            "name": "Bombay Sapphire",
            "price": "MP"
          },
          {
            "name": "Citadelle",
            "price": "MP"
          },
          {
            "name": "Komasa Gin",
            "price": "MP"
          }
        ]
      },
      {
        "name": "Rum",
        "items": [
          {
            "name": "Homere Clement",
            "price": "MP"
          },
          {
            "name": "Rhum J.M. Terroir Volcanique",
            "desc": "Rhum J.M. Terroire Volcanique (Caribbean)",
            "price": "MP"
          },
          {
            "name": "Siesta Key Coconut Rum",
            "desc": "Siesta Key Coconut Rum (Sarasota)",
            "price": "MP"
          },
          {
            "name": "Siesta Key Spiced Rum",
            "desc": "Siesta Key Spiced Rum (Sarasota)",
            "price": "MP"
          },
          {
            "name": "Foursquare Equidem",
            "price": "MP"
          },
          {
            "name": "Planteray O.F.T.D (Caribbean)",
            "price": "MP"
          },
          {
            "name": "Planteray Original Dark",
            "desc": "Planteray Original Dark (Caribbean)",
            "price": "MP"
          },
          {
            "name": "Planteray Cut And Dry",
            "price": "MP"
          },
          {
            "name": "Planteray 3 Star (Caribbean)",
            "price": "MP"
          },
          {
            "name": "Saint Benevolence Clarin",
            "price": "MP"
          },
          {
            "name": "Sol Tarasco Charanda Mushroom",
            "desc": "Sol Tarasco Charanda Mushroom Rum (Mexico)",
            "price": "MP"
          },
          {
            "name": "Hamilton “White Stache” Rum",
            "desc": "(Caribbean)",
            "price": "MP"
          },
          {
            "name": "Hamilton 86 Demerara Rum",
            "price": "MP"
          }
        ]
      },
      {
        "name": "Tequila",
        "items": [
          {
            "name": "Fortaleza (Jalisco)",
            "price": "MP"
          },
          {
            "name": "Fosoforo Mezcal (Puebla)",
            "price": "MP"
          },
          {
            "name": "Vida Mezcal (Oaxaca)",
            "price": "MP"
          },
          {
            "name": "Mijenta Reposado (Jalisco)",
            "price": "MP"
          },
          {
            "name": "Mijenta Blanco (Jalisco)",
            "price": "MP"
          },
          {
            "name": "Teramana Blanco (Jalisco)",
            "price": "MP"
          },
          {
            "name": "Tequila Ocho (Jalisco)",
            "price": "MP"
          },
          {
            "name": "Codigo Rosa (Amatitán)",
            "price": "MP"
          },
          {
            "name": "The Lost Explorer 12yr",
            "desc": "The Lost Explorer 12yr Salmiana (Oaxaca)",
            "price": "MP"
          },
          {
            "name": "The Lost Explorer 10yr Tobala",
            "desc": "(Oaxaca)",
            "price": "MP"
          },
          {
            "name": "The Lost Explorer 8yr Espadin",
            "desc": "(Oaxaca)",
            "price": "MP"
          },
          {
            "name": "La Gritona Reposado (Jalisco)",
            "price": "MP"
          },
          {
            "name": "Arette Artisinal",
            "price": "MP"
          },
          {
            "name": "Arette Reposado (Jalisco)",
            "price": "MP"
          },
          {
            "name": "Arette Blanco (Jalisco)",
            "price": "MP"
          }
        ]
      },
      {
        "name": "Bourbon/Whiskey",
        "items": [
          {
            "name": "Short Barell Cigar Batch",
            "desc": "(Georgia)",
            "price": "MP"
          },
          {
            "name": "Baby Jane (Kentucky)",
            "price": "MP"
          },
          {
            "name": "Bourbon (Vermont)",
            "price": "MP"
          },
          {
            "name": "Whistlepig Snout To Tail 10yr",
            "desc": "(Vermont)",
            "price": "MP"
          },
          {
            "name": "Michter’s Bourbon (Kentucky)",
            "price": "MP"
          },
          {
            "name": "Woodford Reserve (Kentucky)",
            "desc": "Double Oaked",
            "price": "MP"
          },
          {
            "name": "Crown Royal (Canada)",
            "price": "MP"
          },
          {
            "name": "High West Campfire (Utah)",
            "price": "MP"
          },
          {
            "name": "Widow Jane 10yr (New York)",
            "price": "MP"
          },
          {
            "name": "Tullamore Dew (Ireland)",
            "price": "MP"
          },
          {
            "name": "Larceny Bourbon (Kentucky)",
            "price": "MP"
          },
          {
            "name": "Makers Mark (Kentucky)",
            "price": "MP"
          },
          {
            "name": "Angel’s Envy (Kentucky)",
            "price": "MP"
          },
          {
            "name": "Basil Hayden (Kentucky)",
            "price": "MP"
          },
          {
            "name": "Elijah Craig (Kentucky)",
            "price": "MP"
          },
          {
            "name": "Doc Swinsons 5yr (Washington)",
            "price": "MP"
          }
        ]
      },
      {
        "name": "Rye",
        "items": [
          {
            "name": "Michter’s Rye (Kentucky)",
            "price": "MP"
          },
          {
            "name": "Angel’s Envy Rye (Kentucky)",
            "price": "MP"
          },
          {
            "name": "Rittenhouse Rye (Pennsylvania)",
            "price": "MP"
          },
          {
            "name": "Whistlepig 15yr (Vermont)",
            "price": "MP"
          },
          {
            "name": "Whistlepig 12yr (Vermont)",
            "price": "MP"
          },
          {
            "name": "Whistlepig 10yr (Vermont)",
            "price": "MP"
          },
          {
            "name": "Willett Rye (Kentucky)",
            "price": "MP"
          }
        ]
      },
      {
        "name": "Scotch",
        "items": [
          {
            "name": "The Balvenie 12 Doublewood",
            "desc": "(Scotland)",
            "price": "MP"
          },
          {
            "name": "Monkey Shoulder (Scotland)",
            "price": "MP"
          },
          {
            "name": "Compass Box Nectarsotiy",
            "desc": "(Scotland)",
            "price": "MP"
          },
          {
            "name": "Laphroaig (Scotland)",
            "price": "MP"
          },
          {
            "name": "Lagavulin 16yr (Scotland)",
            "price": "MP"
          },
          {
            "name": "Oban 14yr (Scotland)",
            "price": "MP"
          },
          {
            "name": "Johnnie Walker Black",
            "desc": "Scotland",
            "price": "MP"
          },
          {
            "name": "Suntory Toki",
            "price": "MP"
          },
          {
            "name": "Dewars (Scotland)",
            "price": "MP"
          }
        ]
      },
      {
        "name": "Cognac/Armagnac",
        "items": [
          {
            "name": "Bache Gabrielsen Tre Kors",
            "price": "MP"
          },
          {
            "name": "Kelt Commodore Extremely Rare",
            "desc": "Kelt Commodore Extremely Rare Cognac",
            "price": "MP"
          },
          {
            "name": "Larressingle Armagnac VSOP",
            "price": "MP"
          },
          {
            "name": "Darroze Blanche Armagnac",
            "price": "MP"
          },
          {
            "name": "Naud V.S Fine Cognac (France)",
            "price": "MP"
          },
          {
            "name": "Pierre Ferrand 1940 Champagne",
            "desc": "Pierre Ferrand 1940 Champagne Cognac (France)",
            "price": "MP"
          },
          {
            "name": "Meukow V.S.O.P. (France)",
            "price": "MP"
          }
        ]
      },
      {
        "name": "Cordials",
        "items": [
          {
            "name": "Finocetto",
            "price": "MP"
          },
          {
            "name": "Grand Marnier Cuvee",
            "desc": "Grand Marnier Cuvee Louis-Alexandre (France)",
            "price": "MP"
          },
          {
            "name": "Jeppsons Malort (Chicago)",
            "price": "MP"
          },
          {
            "name": "Campari",
            "price": "MP"
          },
          {
            "name": "Aperol",
            "price": "MP"
          },
          {
            "name": "St. George Absinthe",
            "desc": "(California)",
            "price": "MP"
          },
          {
            "name": "Yellow Chartreuse",
            "price": "MP"
          },
          {
            "name": "Green Chartreuse",
            "price": "MP"
          },
          {
            "name": "Montenegro Amaro",
            "price": "MP"
          },
          {
            "name": "Braulio",
            "price": "MP"
          },
          {
            "name": "Amaro Nonino",
            "price": "MP"
          },
          {
            "name": "Benedictine",
            "price": "MP"
          },
          {
            "name": "Averna Amaro",
            "price": "MP"
          },
          {
            "name": "Angostura Amaro",
            "price": "MP"
          },
          {
            "name": "Pernod",
            "price": "MP"
          },
          {
            "name": "Fraretti Biscotti",
            "price": "MP"
          },
          {
            "name": "Lazzaroni Amaretto",
            "price": "MP"
          }
        ]
      }
    ]
  }
];
