// Generated by scripts/fetch-shop.mjs — do not edit by hand.
// Source: the live WooCommerce store at https://shop.rebellionwinebar.com.
// Re-run `node scripts/fetch-shop.mjs` when stock or pricing changes.
//
// 13 products, pulled 2026-09-03.

export type Product = {
  name: string;
  slug: string;
  /** The artwork on it — two shirts share a name and differ only by this. */
  design: string;
  /** Pre-formatted, and "From $x" wherever the larger sizes cost more. */
  price: string;
  /** The product's page on the store, where sizes are chosen and the sale happens. */
  href: string;
  image: string;
  alt: string;
  colors: string[];
  sizes: string[];
};

export const products: Product[] = [
  {
    "name": "Jersey Crop",
    "slug": "jersey-crop",
    "design": "Put A Cork In It",
    "price": "From $30",
    "href": "https://shop.rebellionwinebar.com/shop/jersey-crop/",
    "image": "/shop/jersey-crop.webp",
    "alt": "Jersey Crop — Rebellion merch",
    "colors": [
      "White"
    ],
    "sizes": [
      "Small",
      "Medium",
      "Large",
      "X-Large",
      "2X-Large"
    ]
  },
  {
    "name": "Crop T Shirt",
    "slug": "crop-t-shirt",
    "design": "Rebel Against The Ordinary",
    "price": "$25",
    "href": "https://shop.rebellionwinebar.com/shop/crop-t-shirt/",
    "image": "/shop/crop-t-shirt.webp",
    "alt": "Crop T Shirt — Rebellion merch",
    "colors": [
      "White"
    ],
    "sizes": [
      "XS/S",
      "M/L"
    ]
  },
  {
    "name": "Flowy Side Slit Tank",
    "slug": "flowy-side-slit-tank",
    "design": "Rebellion Logo",
    "price": "From $27",
    "href": "https://shop.rebellionwinebar.com/shop/flowy-side-slit-tank/",
    "image": "/shop/flowy-side-slit-tank.webp",
    "alt": "Flowy Side Slit Tank — Rebellion merch",
    "colors": [
      "White Slub"
    ],
    "sizes": [
      "Small",
      "Medium",
      "Large",
      "X-Large",
      "2X-Large"
    ]
  },
  {
    "name": "Sleeve Raglan",
    "slug": "sleeve-raglan",
    "design": "Rebellion Logo",
    "price": "From $36",
    "href": "https://shop.rebellionwinebar.com/shop/sleeve-raglan/",
    "image": "/shop/sleeve-raglan.webp",
    "alt": "Sleeve Raglan — Rebellion merch",
    "colors": [
      "Black"
    ],
    "sizes": [
      "Small",
      "Medium",
      "Large",
      "X-Large",
      "2X-Large"
    ]
  },
  {
    "name": "V Shirt",
    "slug": "v-shirt",
    "design": "Cocoa Village",
    "price": "From $22",
    "href": "https://shop.rebellionwinebar.com/shop/v-shirt/",
    "image": "/shop/v-shirt.webp",
    "alt": "V Shirt — Rebellion merch",
    "colors": [
      "Black",
      "White"
    ],
    "sizes": [
      "X-Small",
      "Small",
      "Medium",
      "Large",
      "X-Large",
      "2X-Large"
    ]
  },
  {
    "name": "Flowy High Neck Tank",
    "slug": "flowy-high-neck-tank",
    "design": "Put A Cork In It",
    "price": "From $27",
    "href": "https://shop.rebellionwinebar.com/shop/flowy-high-neck-tank/",
    "image": "/shop/flowy-high-neck-tank.webp",
    "alt": "Flowy High Neck Tank — Rebellion merch",
    "colors": [
      "White"
    ],
    "sizes": [
      "Small",
      "Medium",
      "Large",
      "X-Large",
      "2X-Large"
    ]
  },
  {
    "name": "Festival Tank",
    "slug": "festival-tank",
    "design": "Cocoa Village",
    "price": "From $30",
    "href": "https://shop.rebellionwinebar.com/shop/festival-tank/",
    "image": "/shop/festival-tank.webp",
    "alt": "Festival Tank — Rebellion merch",
    "colors": [
      "Black"
    ],
    "sizes": [
      "X-Small",
      "Small",
      "Medium",
      "Large",
      "X-Large",
      "2X-Large"
    ]
  },
  {
    "name": "Rebellion Mug",
    "slug": "rebellion-mug",
    "design": "Holds 11oz (325ml)",
    "price": "$14",
    "href": "https://shop.rebellionwinebar.com/shop/rebellion-mug/",
    "image": "/shop/rebellion-mug.webp",
    "alt": "Rebellion Mug — Rebellion merch",
    "colors": [
      "White"
    ],
    "sizes": [
      "11oz"
    ]
  },
  {
    "name": "Baseball T-Shirt",
    "slug": "baseball-t-shirt-2",
    "design": "Logotype",
    "price": "From $30",
    "href": "https://shop.rebellionwinebar.com/shop/baseball-t-shirt-2/",
    "image": "/shop/baseball-t-shirt-2.webp",
    "alt": "Baseball T-Shirt — Rebellion merch",
    "colors": [
      "Grey/Maroon Triblend",
      "Deep Heather/Black"
    ],
    "sizes": [
      "Small",
      "Medium",
      "Large",
      "X-Large",
      "2X-Large"
    ]
  },
  {
    "name": "Unisex Sponge Fleece Full-Zip Hoodie",
    "slug": "unisex-sponge-fleece-full-zip-hoodie",
    "design": "Skull Logo",
    "price": "From $42",
    "href": "https://shop.rebellionwinebar.com/shop/unisex-sponge-fleece-full-zip-hoodie/",
    "image": "/shop/unisex-sponge-fleece-full-zip-hoodie.webp",
    "alt": "Unisex Sponge Fleece Full-Zip Hoodie — Rebellion merch",
    "colors": [
      "Grey Triblend"
    ],
    "sizes": [
      "X-Small",
      "Small",
      "Medium",
      "Large",
      "X-Large",
      "2X-Large"
    ]
  },
  {
    "name": "Rebellion Signature Tee",
    "slug": "rebellion-signature-tee",
    "design": "The Gilden Hammer Unisex t-shirt is one of the most popular fashion t-shirts",
    "price": "From $27.30",
    "href": "https://shop.rebellionwinebar.com/shop/rebellion-signature-tee/",
    "image": "/shop/rebellion-signature-tee.webp",
    "alt": "Rebellion Signature Tee — Rebellion merch",
    "colors": [
      "Black"
    ],
    "sizes": [
      "Small",
      "Medium",
      "Large",
      "X-Large",
      "2X-Large",
      "3X-Large",
      "4X-Large",
      "5X-Large"
    ]
  },
  {
    "name": "Baseball T-Shirt",
    "slug": "baseball-t-shirt",
    "design": "Skull Logo",
    "price": "From $30",
    "href": "https://shop.rebellionwinebar.com/shop/baseball-t-shirt/",
    "image": "/shop/baseball-t-shirt.webp",
    "alt": "Baseball T-Shirt — Rebellion merch",
    "colors": [
      "Deep Heather/Black",
      "Grey/Maroon Triblend"
    ],
    "sizes": [
      "Small",
      "Medium",
      "Large",
      "X-Large",
      "2X-Large"
    ]
  },
  {
    "name": "Signature Hat",
    "slug": "signature-hat",
    "design": "The Signature Rebellion Hat is a peached cotton twill dad cap made from 100% Cotton",
    "price": "$20",
    "href": "https://shop.rebellionwinebar.com/shop/signature-hat/",
    "image": "/shop/signature-hat.webp",
    "alt": "Signature Hat — Rebellion merch",
    "colors": [
      "Black"
    ],
    "sizes": [
      "OS"
    ]
  }
];
