#!/usr/bin/env python3
"""Install the licensed display face, if there is one.

The approved system wants Canela or Editorial New on headlines. Both are
commercial retail fonts, neither was in the hand-off, and neither can be
fetched from anywhere legitimate — so the site ships on Cormorant Garamond and
this script is the door the licensed face walks through.

    1. drop the licensed files into brand/fonts/display/
    2. python3 scripts/build-display-font.py
    3. rebuild

Nothing else changes. Every headline on the site resolves through one family
name, "Rebellion Display", so which foundry ends up winning is invisible to the
components.

When the folder is empty this writes an empty stylesheet, "Rebellion Display"
resolves to nothing, and `--font-display` falls straight through to Cormorant.
That matters: declaring a @font-face for a file that is not there would 404 on
every page load, and the fallback would look identical while quietly costing a
request. Nothing is a better default than something broken.

Weights map to the two the site actually sets — `.display` at 600 and
`.display-soft` at 500 (see app/globals.css):

    *light*, *regular*, *book*, *medium*   -> 500
    *semibold*, *demi*, *bold*, *black*    -> 600

Italics are detected from the filename and kept as a separate face.
"""

import re
import shutil
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "brand" / "fonts" / "display"
OUT = ROOT / "public" / "fonts"
STYLESHEET = ROOT / "app" / "generated-display.css"

FAMILY = "Rebellion Display"
ACCEPTED = {".otf", ".ttf", ".woff2", ".woff"}
UNICODES = "U+0020-007E,U+00A0-00FF,U+2010-2015,U+2018-201A,U+201C-201E,U+2022,U+2026"

HEAVY = ("semibold", "demibold", "demi", "bold", "black", "heavy")


def weight_of(stem: str) -> int:
    low = stem.lower()
    return 600 if any(k in low for k in HEAVY) else 500


def is_italic(stem: str) -> bool:
    return bool(re.search(r"italic|oblique", stem, re.I))


def main() -> int:
    SRC.mkdir(parents=True, exist_ok=True)
    OUT.mkdir(parents=True, exist_ok=True)

    sources = sorted(p for p in SRC.iterdir() if p.suffix.lower() in ACCEPTED)
    if not sources:
        STYLESHEET.write_text(
            "/* Generated by scripts/build-display-font.py — do not edit.\n"
            "   No licensed display face is installed, so headlines fall through\n"
            "   to Cormorant Garamond. Drop Canela or Editorial New into\n"
            "   brand/fonts/display/ and re-run the script. */\n"
        )
        for stale in OUT.glob("display-*.woff2"):
            stale.unlink()
        print("no licensed display face found — headlines stay on Cormorant Garamond")
        print(f"drop the files into {SRC.relative_to(ROOT)}/ and run this again")
        return 0

    faces = []
    for src in sources:
        weight = weight_of(src.stem)
        style = "italic" if is_italic(src.stem) else "normal"
        dst = OUT / f"display-{weight}{'-italic' if style == 'italic' else ''}.woff2"

        if src.suffix.lower() == ".woff2":
            shutil.copyfile(src, dst)
        else:
            subprocess.run(
                [
                    sys.executable, "-m", "fontTools.subset", str(src),
                    f"--unicodes={UNICODES}",
                    "--layout-features=kern,liga,calt,onum,lnum",
                    "--flavor=woff2", "--desubroutinize",
                    f"--output-file={dst}",
                ],
                check=True,
            )
        faces.append((weight, style, dst))
        print(f"{src.name:38s} -> {dst.name}  ({weight} {style}, {dst.stat().st_size // 1024}KB)")

    blocks = "\n\n".join(
        "@font-face {\n"
        f'  font-family: "{FAMILY}";\n'
        f"  src: url(/fonts/{dst.name}) format(\"woff2\");\n"
        f"  font-weight: {weight};\n"
        f"  font-style: {style};\n"
        "  font-display: swap;\n"
        "}"
        for weight, style, dst in faces
    )
    STYLESHEET.write_text(
        "/* Generated by scripts/build-display-font.py — do not edit.\n"
        f"   Installed from brand/fonts/display/. `--font-display` in\n"
        f'   app/globals.css resolves "{FAMILY}" ahead of Cormorant. */\n\n'
        + blocks
        + "\n"
    )
    print(f"\nwrote {STYLESHEET.relative_to(ROOT)} — headlines now use the licensed face")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
