/**
 * Pull the merch catalogue from WooCommerce and regenerate lib/shop-data.ts.
 *
 *     node scripts/fetch-shop.mjs
 *
 * The store is a separate WordPress at shop.rebellionwinebar.com — group-wide
 * "Rebellion" apparel, which is why the bistro sells it too. This site shows the
 * catalogue in its own design and hands off to WooCommerce at the buy click,
 * because every product is a variable one: sizes and colours live on the
 * product page, and rebuilding that picker here would mean rebuilding the cart
 * with it.
 *
 * Nothing here writes to the store. It reads the public Store API, the same one
 * the shop's own front end uses, and copies the product photography into
 * /public/shop so the page does not depend on that host staying up.
 */
import { writeFileSync, mkdirSync, readdirSync, rmSync } from "node:fs";
import { fileURLToPath } from "node:url";
import path from "node:path";
import sharp from "sharp";

const STORE = process.env.SHOP_ORIGIN ?? "https://shop.rebellionwinebar.com";
const ENDPOINT = `${STORE}/wp-json/wc/store/v1/products?per_page=100`;

const root = path.dirname(fileURLToPath(new URL("../package.json", import.meta.url)));
const IMAGE_DIR = path.join(root, "public", "shop");

/** The card renders at ~420px wide; 840 covers a 2× screen with room to spare. */
const IMAGE_WIDTH = 840;

/** WooCommerce returns money in minor units — "2730" is $27.30. */
function money(minor, unit = 2) {
  const n = Number(minor) / 10 ** unit;
  return Number.isInteger(n) ? `${n}` : n.toFixed(2);
}

/**
 * Most items cost more in the larger sizes, so the store carries a range. A
 * single number would be a promise the checkout might not keep.
 */
function priceLabel(prices) {
  const unit = prices.currency_minor_unit ?? 2;
  const range = prices.price_range;
  if (range && range.min_amount !== range.max_amount) {
    return `From $${money(range.min_amount, unit)}`;
  }
  return `$${money(prices.price ?? range?.min_amount, unit)}`;
}

const stripTags = (s) => (s ?? "").replace(/<[^>]*>/g, " ");

/** The store's copy is full of HTML entities — WordPress encodes on the way out. */
function decode(s) {
  return stripTags(s)
    .replace(/&#(\d+);/g, (_, n) => String.fromCharCode(Number(n)))
    .replace(/&#x([0-9a-f]+);/gi, (_, n) => String.fromCharCode(parseInt(n, 16)))
    .replace(/&amp;/g, "&")
    .replace(/&quot;/g, '"')
    .replace(/&nbsp;/g, " ")
    .replace(/\s+/g, " ")
    .trim();
}

const attr = (product, name) =>
  (product.attributes ?? [])
    .find((a) => a.name?.toLowerCase() === name)
    ?.terms?.map((t) => decode(t.name)) ?? [];

/**
 * Sizes come back in whatever order the store lists them, which is sometimes
 * largest-first. Ordering them by how clothes are actually sized reads better
 * than alphabetically, and anything unrecognised keeps its place at the end.
 */
const SIZE_RANK = [
  "XX-Small", "X-Small", "XS/S", "Small", "M/L", "Medium", "Large",
  "X-Large", "2X-Large", "3X-Large", "4X-Large", "5X-Large",
];
const bySize = (a, b) => {
  const ia = SIZE_RANK.indexOf(a);
  const ib = SIZE_RANK.indexOf(b);
  if (ia === -1 || ib === -1) return 0;
  return ia - ib;
};

async function saveImage(url, slug) {
  const res = await fetch(url);
  if (!res.ok) throw new Error(`image ${res.status} for ${slug}`);
  const buf = Buffer.from(await res.arrayBuffer());
  const file = `${slug}.webp`;
  await sharp(buf)
    .resize({ width: IMAGE_WIDTH, withoutEnlargement: true })
    .webp({ quality: 82 })
    .toFile(path.join(IMAGE_DIR, file));
  return `/shop/${file}`;
}

async function main() {
  const res = await fetch(ENDPOINT, { headers: { accept: "application/json" } });
  if (!res.ok) throw new Error(`Store API returned ${res.status}`);
  const raw = await res.json();

  mkdirSync(IMAGE_DIR, { recursive: true });
  for (const f of readdirSync(IMAGE_DIR)) rmSync(path.join(IMAGE_DIR, f));

  const products = [];
  for (const p of raw) {
    if (!p.is_in_stock || !p.is_purchasable) continue;

    const image = p.images?.[0]?.src ? await saveImage(p.images[0].src, p.slug) : null;
    if (!image) continue;

    // Two shirts share the name "Baseball T-Shirt" and differ only by artwork,
    // so the design note is what tells them apart on the page. Some are written
    // in quotes and some are not; the page sets them all the same way.
    const design = decode(p.description)
      .split(". ")[0]
      .replace(/^["\u201c\u2018']+|["\u201d\u2019']+$/g, "")
      .slice(0, 90);

    products.push({
      name: decode(p.name),
      slug: p.slug,
      design,
      price: priceLabel(p.prices),
      href: p.permalink,
      image,
      alt: decode(p.images[0].alt) || `${decode(p.name)} — Rebellion merch`,
      colors: attr(p, "color"),
      sizes: attr(p, "size").sort(bySize),
    });
  }

  const file = `// Generated by scripts/fetch-shop.mjs — do not edit by hand.
// Source: the live WooCommerce store at ${STORE}.
// Re-run \`node scripts/fetch-shop.mjs\` when stock or pricing changes.
//
// ${products.length} products, pulled ${new Date().toISOString().slice(0, 10)}.

export type Product = {
  name: string;
  slug: string;
  /** The artwork on it — two shirts share a name and differ only by this. */
  design: string;
  /** Pre-formatted, and "From $x" wherever the larger sizes cost more. */
  price: string;
  /** The product's page on the store, where sizes are chosen and the sale happens. */
  href: string;
  image: string;
  alt: string;
  colors: string[];
  sizes: string[];
};

export const products: Product[] = ${JSON.stringify(products, null, 2)};
`;

  writeFileSync(path.join(root, "lib", "shop-data.ts"), file);
  console.log(`Wrote lib/shop-data.ts — ${products.length} products.`);
  for (const p of products) {
    console.log(`  ${p.name.padEnd(36)} ${p.price.padEnd(10)} ${p.sizes.length} sizes`);
  }
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
